// Code generated by protoc-gen-go. DO NOT EDIT.
// source: model_swagger.proto

/*
Package model_swagger is a generated protocol buffer package.

It is generated from these files:
	model_swagger.proto

It has these top-level messages:
	GetSwaggerJsonRequest
	GetSwaggerJsonResponse
*/
package model_swagger

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "gitee.com/kelvins-io/common/proto/google/api"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetSwaggerJsonRequest struct {
	Timestamp int64  `protobuf:"varint,1,opt,name=timestamp" json:"timestamp,omitempty"`
	Sign      string `protobuf:"bytes,2,opt,name=sign" json:"sign,omitempty"`
}

func (m *GetSwaggerJsonRequest) Reset()                    { *m = GetSwaggerJsonRequest{} }
func (m *GetSwaggerJsonRequest) String() string            { return proto.CompactTextString(m) }
func (*GetSwaggerJsonRequest) ProtoMessage()               {}
func (*GetSwaggerJsonRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GetSwaggerJsonRequest) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *GetSwaggerJsonRequest) GetSign() string {
	if m != nil {
		return m.Sign
	}
	return ""
}

type GetSwaggerJsonResponse struct {
	Json string `protobuf:"bytes,1,opt,name=json" json:"json,omitempty"`
}

func (m *GetSwaggerJsonResponse) Reset()                    { *m = GetSwaggerJsonResponse{} }
func (m *GetSwaggerJsonResponse) String() string            { return proto.CompactTextString(m) }
func (*GetSwaggerJsonResponse) ProtoMessage()               {}
func (*GetSwaggerJsonResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetSwaggerJsonResponse) GetJson() string {
	if m != nil {
		return m.Json
	}
	return ""
}

func init() {
	proto.RegisterType((*GetSwaggerJsonRequest)(nil), "model_swagger.GetSwaggerJsonRequest")
	proto.RegisterType((*GetSwaggerJsonResponse)(nil), "model_swagger.GetSwaggerJsonResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for SwaggerModelService service

type SwaggerModelServiceClient interface {
	GetSwaggerJson(ctx context.Context, in *GetSwaggerJsonRequest, opts ...grpc.CallOption) (*GetSwaggerJsonResponse, error)
}

type swaggerModelServiceClient struct {
	cc *grpc.ClientConn
}

func NewSwaggerModelServiceClient(cc *grpc.ClientConn) SwaggerModelServiceClient {
	return &swaggerModelServiceClient{cc}
}

func (c *swaggerModelServiceClient) GetSwaggerJson(ctx context.Context, in *GetSwaggerJsonRequest, opts ...grpc.CallOption) (*GetSwaggerJsonResponse, error) {
	out := new(GetSwaggerJsonResponse)
	err := grpc.Invoke(ctx, "/model_swagger.SwaggerModelService/GetSwaggerJson", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SwaggerModelService service

type SwaggerModelServiceServer interface {
	GetSwaggerJson(context.Context, *GetSwaggerJsonRequest) (*GetSwaggerJsonResponse, error)
}

func RegisterSwaggerModelServiceServer(s *grpc.Server, srv SwaggerModelServiceServer) {
	s.RegisterService(&_SwaggerModelService_serviceDesc, srv)
}

func _SwaggerModelService_GetSwaggerJson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSwaggerJsonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwaggerModelServiceServer).GetSwaggerJson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model_swagger.SwaggerModelService/GetSwaggerJson",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwaggerModelServiceServer).GetSwaggerJson(ctx, req.(*GetSwaggerJsonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SwaggerModelService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "model_swagger.SwaggerModelService",
	HandlerType: (*SwaggerModelServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSwaggerJson",
			Handler:    _SwaggerModelService_GetSwaggerJson_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "model_swagger.proto",
}

func init() { proto.RegisterFile("model_swagger.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 253 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0xc1, 0x4a, 0xf3, 0x40,
	0x10, 0xc7, 0x49, 0xbf, 0x0f, 0x21, 0x0b, 0x7a, 0xd8, 0x52, 0x2d, 0x45, 0xa1, 0x04, 0x85, 0x1e,
	0x24, 0x83, 0x7a, 0xf7, 0x2a, 0x0a, 0x5e, 0xd2, 0x07, 0x90, 0x35, 0x0e, 0xcb, 0x4a, 0x76, 0x26,
	0x66, 0xc6, 0x8a, 0xe0, 0xc9, 0x57, 0xe8, 0xa3, 0xf9, 0x0a, 0x3e, 0x88, 0x74, 0x53, 0x90, 0x88,
	0xe0, 0x6d, 0x18, 0x7e, 0xf3, 0xe3, 0x3f, 0x7f, 0x33, 0x8e, 0xfc, 0x80, 0xcd, 0x9d, 0xbc, 0x38,
	0xef, 0xb1, 0x2b, 0xdb, 0x8e, 0x95, 0xed, 0xee, 0x60, 0x39, 0xbb, 0xf4, 0x41, 0xcb, 0xf8, 0x2a,
	0x75, 0x17, 0xcb, 0x9a, 0xc0, 0x73, 0xe3, 0xc8, 0x43, 0xcd, 0x31, 0x32, 0x41, 0xba, 0x00, 0xcf,
	0xec, 0x1b, 0x04, 0xd7, 0x06, 0x70, 0x44, 0xac, 0x4e, 0x03, 0x93, 0xf4, 0xba, 0xe2, 0xda, 0x4c,
	0xae, 0x50, 0x97, 0xbd, 0xed, 0x46, 0x98, 0x2a, 0x7c, 0x7a, 0x46, 0x51, 0x7b, 0x68, 0x72, 0x0d,
	0x11, 0x45, 0x5d, 0x6c, 0xa7, 0xd9, 0x3c, 0x5b, 0xfc, 0xab, 0xbe, 0x17, 0xd6, 0x9a, 0xff, 0x12,
	0x3c, 0x4d, 0x47, 0xf3, 0x6c, 0x91, 0x57, 0x69, 0x2e, 0x4e, 0xcd, 0xfe, 0x4f, 0x95, 0xb4, 0x4c,
	0x82, 0x1b, 0xfa, 0x51, 0x98, 0x92, 0x26, 0xaf, 0xd2, 0x7c, 0xbe, 0xce, 0xcc, 0x78, 0xcb, 0xde,
	0x6e, 0x3e, 0x5a, 0x62, 0xb7, 0x0a, 0x35, 0xda, 0x37, 0xb3, 0x37, 0xb4, 0xd8, 0xe3, 0x72, 0xd8,
	0xc3, 0xaf, 0x79, 0x67, 0x27, 0x7f, 0x50, 0x7d, 0x94, 0xe2, 0xe8, 0xfd, 0xe3, 0x73, 0x3d, 0x3a,
	0xb0, 0x13, 0x58, 0x9d, 0xc1, 0x96, 0x85, 0x74, 0x09, 0x1e, 0xf5, 0x7e, 0x27, 0xb5, 0x72, 0xf1,
	0x15, 0x00, 0x00, 0xff, 0xff, 0x00, 0x84, 0x29, 0x2c, 0x7b, 0x01, 0x00, 0x00,
}
